@startuml testt
actor client
node app
node car
node tshirt

car -> app
app -> client
client -> tshirt
tshirt -> car
@enduml

![your-UML-diagram-name](http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/ramaaorella/test/main/test.iuml)
